In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# load the datasets
from sklearn import datasets
iris = datasets.load_iris()
list(iris.keys())

['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']

In [3]:
# extract the input features and target labels
X = iris["data"]
y = iris["target"]

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# train the model using LogisticRegression with multi classification
from sklearn.linear_model import LogisticRegression
softmax_reg = LogisticRegression(multi_class="multinomial",solver="lbfgs", C=10, max_iter=1000)
softmax_reg.fit(X_train, y_train)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
# make predictions
y_pred = softmax_reg.predict(X_test)
y_proba = softmax_reg.predict_proba(X_test)
print('Prediction for X_test[0:10]:', y_pred[0:10])
print('\nActual labels y_test[0:10]:', y_test[0:10]) 
print('\nProbalitiy for X_test[0:5]\n', y_proba[0:5])

Prediction for X_test[0:10]: [2 1 0 2 0 2 0 1 1 1]

Actual labels y_test[0:10]: [2 1 0 2 0 2 0 1 1 1]

Probalitiy for X_test[0:5]
 [[9.19487973e-08 2.23576475e-03 9.97764143e-01]
 [5.59347440e-04 9.98444182e-01 9.96470102e-04]
 [9.98453384e-01 1.54661590e-03 2.90216539e-15]
 [2.23308608e-10 2.59151166e-03 9.97408488e-01]
 [9.94719582e-01 5.28041772e-03 1.35293037e-13]]


In [12]:
# Evaluate the model using the Confusion Matrix and Classification Report
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
print('Confusion Matrix:\n', cm)
print('Classification Report:\n', cr)

Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

