## Creating Arrays and Matrices in Python

In [2]:
# importing Numerical Python Library
import numpy as np

In [4]:
# creating from list
a_list = [1, 2, 3, 4, 5]

A = np.array(a_list)

print ('One-dimensional array from list:', A)

One-dimensional array from list: [1 2 3 4 5]


In [5]:
# creating from tuple
b_tuple = (5, 6, 7, 8, 9)

B = np.array(b_tuple)

print('One-dimensional array from tuple:', B)

One-dimensional array from tuple: [5 6 7 8 9]


In [7]:
# by calling array function and directly assigning elements
# one-dimensional array
X_1d = np.array([1, 2, 3, 4])

# two-dimensional array
X_2d = np.array([[1, 2, 3], [4, 5, 6]])

print('One-dimensional array:', X_1d)    # notice a sigle-pair square brackets for 1-dimensional array
print('Two-dimensional array:\n', X_2d)  # notice a two-pair square brackets for 2-dimensional array 

One-dimensional array: [1 2 3 4]
Two-dimensional array:
 [[1 2 3]
 [4 5 6]]


In [12]:
# by np.arange function to instantiate with pre-defined no. of elements
# 1-dimensional array with 10 elements
C = np.arange(10)

# 1-dimensional array starting with 0 and 4
D = np.arange(0, 5)

print('1-dimensional array with 10 elements:', C)
print('1-dimensional array starting from 0 to 4:', D)

1-dimensional array with 10 elements: [0 1 2 3 4 5 6 7 8 9]
1-dimensional array starting from 0 to (5-1): [0 1 2 3 4]


In [38]:
# using np.arange function with specified step and dtype
E = np.arange(0, 11, 2, dtype='float32')

print('1-dimensional array:', E)
print(E.dtype)

1-dimensional array: [ 0.  2.  4.  6.  8. 10.]
float32


In [29]:
# creating array with zeros or ones with specified array size, default type is 'float'
y_zeros = np.zeros((5))

X_zeros = np.zeros((3, 3))

X_ones = np.ones((2, 4), dtype='int32')

print('1-dimensional array with 0s:\n', y_zeros)
print('\n2-dimensional array with 0s:\n',X_zeros)
print('\n2-dimensional array with 1s:\n',X_ones)

1-dimensional array with 0s:
 [0. 0. 0. 0. 0.]

2-dimensional array with 0s:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2-dimensional array with 1s:
 [[1 1 1 1]
 [1 1 1 1]]


In [87]:
# using np.linspace fuction to create required no. of elements from the start to end
arr1 = np.linspace(0, 5, 11)

print('1-dimensional array from 0 to 5 with n=11:\n', arr1)

1-dimensional array from 0 to 5 with n=11:
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


## Shape Manipulation

In [61]:
# determining the shape of array using shape property
print('Shape of arr1: ', arr1.shape)
print('Notice the array construction with comma after number of elements.\
       \nThis is not qualified as row vector in matrix operation in Python')

Shape of arr1:  (11,)
Notice the array construction with comma after number of elements.       
This is not qualified as row vector in matrix operation in Python


In [52]:
# to make the array considered as row vector in matrix operation, reshape it to 1-dimensional matrix
arr1_vec = arr1.reshape(1,11)

print('Reshape array to vector:\n', arr1_vec)
print('\nShape of new vector:', arr1_vec.shape)

Reshape array to vector:
 [[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]]

Shape of new vector: (1, 11)


In [54]:
# to make arr1 as column vector
arr1_col = arr1.reshape(11,1)

print(arr1_col)

[[0. ]
 [0.5]
 [1. ]
 [1.5]
 [2. ]
 [2.5]
 [3. ]
 [3.5]
 [4. ]
 [4.5]
 [5. ]]


In [78]:
# to create 1-dimensional array and reshape into 2-dimensional array
arr2 = np.arange(20).reshape(4, 5)

print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [141]:
# to flatten the mxn-array
arr2.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [154]:
# to resize array to smaller size
np.resize(arr2, (5,2))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [155]:
# to resize array to larger size
np.resize(arr2, (6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15]])

## Accessing Array / Matrix Element

In [63]:
# to access element '6' in arr2 : second row (row-index=1) and second column (col-index=1)
elem = arr2[1, 1]

print('Element at arr2[1,1]:', elem)

Element at arr2[1,1]: 6


In [81]:
# to get elements from 2nd & 3rd rows of 3rd column
arr_sub0 = arr2[1:3, 2:3]
arr_sub0

array([[ 7],
       [12]])

In [65]:
# to get all elements from 1st to 3rd column
arr2_sub1 = arr2[:, :3]
arr2_sub1

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [67]:
# to get all elements from 4th to last column
arr2_sub2 = arr2[:, 3:]
arr2_sub2

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [74]:
# to get all elements from 2nd to 4th column
arr2_sub3 = arr2[:, 1:4]
arr2_sub3

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [71]:
# to get all columns except the last one
arr2_sub4 = arr2[:, :-1]
arr2_sub4

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [83]:
# to get the firt 2-rows
arr2_sub5 = arr2[:2, :]
arr2_sub5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
# to get last column
arr2_sub6 = arr2[:, 4:5]
arr2_sub6

array([[ 4],
       [ 9],
       [14],
       [19]])

## Matrix Operation

### Addition
Note: Same rules will be applied to Subtraction of matrices

In [91]:
# adding scalar to row vector : scalar is added to every element of vector
y = 100
Ah = np.arange(5)
print('Scalar, y =', y)
print('Row vector, Ah =', Ah)
print('Ah + y : ', (Ah + y))

Scalar, y = 100
Row vector, Ah = [0 1 2 3 4]
Ah + y :  [100 101 102 103 104]


In [94]:
# adding scalar to column vector : scalar is added to every element of vector
Av = Ah.reshape(5,1)
print('Column vector, Av:\n', Av)
print('Av + y:\n', (Av + y))

Column vector, Av:
 [[0]
 [1]
 [2]
 [3]
 [4]]
Av + y:
 [[100]
 [101]
 [102]
 [103]
 [104]]


In [97]:
# adding scalar to 2-dimensional matrix : element-wise addition, scalar is added to every element of a matrix
W = np.arange(8).reshape(4,2)
print('2d matrix, W:\n', W)
print('W + y:\n', (W + y))

2d matrix, W:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
W + y:
 [[100 101]
 [102 103]
 [104 105]
 [106 107]]


In [107]:
# adding a vector and 2d-matrix : element-wise addition, element of vector is added to every element of 2d matrix
u = np.arange(1,5).reshape(4,1)
v = np.arange(1,9).reshape(4,2)
print('Column vector, u (4x1):\n', u)
print('2d matrix, v (4x2):\n', v)
print('u + v (4x2):\n', (u + v))

Column vector, u (4x1):
 [[1]
 [2]
 [3]
 [4]]
2d matrix, v (4x2):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
u + v (4x2):
 [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


In [111]:
# adding 2 matrices with equal shape : element-wise addition   
x = np.ones((4,2), dtype='int32')
y = np.arange(1,9).reshape(4,2)
print('matrix x (4x2):\n', x)
print('matrix y (4x2):\n', y)
print('x + y (4x2):\n', (x + y))

matrix x (4x2):
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]
matrix y (4x2):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
x + y (4x2):
 [[2 3]
 [4 5]
 [6 7]
 [8 9]]


### Multiplication

In [116]:
# multiplying scalar to vector : scalar is multiplied to every element of a vector
a = 10
b = np.arange(1,5).reshape(4,1)
print('b (4x1):\n', b)
print ('b x a (4x1):\n', (b*a))

b (4x1):
 [[1]
 [2]
 [3]
 [4]]
b x a (4x1):
 [[10]
 [20]
 [30]
 [40]]


In [119]:
# multiplying 2-vectors with same shape : element-wise multiplication
c = np.arange(10,50, 10).reshape(4,1)
print('b (4x1):\n', b)
print('c (4x1):\n', c)
print('b x c (4x1):\n', (b*c))

b (4x1):
 [[1]
 [2]
 [3]
 [4]]
c (4x1):
 [[10]
 [20]
 [30]
 [40]]
b x c (4x1):
 [[ 10]
 [ 40]
 [ 90]
 [160]]


In [125]:
# to get the sum of all elements of the product of b and c vectors above, transpose b vector then dot multiply by c
# this will match the b-column with c-rows, the result is 1x1
bc = (b.T).dot(c)
print('b-transpose (1x4):', b.T)
print('c (4x1):\n', c)
print('b.T.dot(c) :', bc)

b-transpose (1x4): [[1 2 3 4]]
c (4x1):
 [[10]
 [20]
 [30]
 [40]]
b.T.dot(c) : [[300]]


In [131]:
# m : no.of rows,  n : no. of columns
# for multiplication of 2-matrices, the n of 1st matrix  = m of the 2nd matrix, the product has dimension: m of 1st x n of 2nd
x = np.arange(1,9).reshape(4,2)
y = np.arange(1,5).reshape(2,2)

# to multiply 2-matrices with different shape(i,e. 4x2 * 2x2), use .dot operator
z = x.dot(y)

print('x (4x2):\n', x)
print('y (2x2):\n', y)
print('x .dot (y) (4x2):\n', z)

x (4x2):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
y (2x2):
 [[1 2]
 [3 4]]
x .dot (y) (4x2):
 [[ 7 10]
 [15 22]
 [23 34]
 [31 46]]


### Division

In [138]:
# Division of matrices will follow same rules as multiplication.
# Dot product can be applied by using 1/matrix
z = x.dot(1/y)
print('x.dot(1/y) :\n', z)

x.dot(1/y) :
 [[1.66666667 1.        ]
 [4.33333333 2.5       ]
 [7.         4.        ]
 [9.66666667 5.5       ]]


## Linear Algeabra

In [160]:
# create 3x3 matrix
X = np.arange(1,10).reshape(3,3)
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
# transpose the matrix by mirroring at the diagonal
X.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [162]:
# matrix inverse - only for square matrix
np.linalg.inv(X)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [167]:
# to apply pseudo-inverse matrix
np.linalg.pinv(X)

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02,  1.38777878e-16,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [165]:
# to create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])